project:
  type: website
  output-dir: docs
  resources:
    - sta199-f22-1-syllabus.pdf
    - slides/27-interactive-web-apps.pdf
    - /data/

website:
  page-navigation: true
  title: "STA 199"
  description: "Homepage for STA 199 - Introduction to Data Science at Duke University, Spring 2023, Section 1."
  site-url: "https://sta199-f22-1.github.io/"

  repo-url: https://github.com/sta199-f22-1/sta199-f22-1.github.io/
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#2774AE" # nice blue -- Spring 2023
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/sta199-sp23-1
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: people-fill
        href: https://docs.google.com/spreadsheets/d/16gf9dQ_41V628vKvFdS95JBOUKYSjuxJBo7OzPye-SI/edit?usp=sharing
        text: "Office Hours"

        # menu:
        #   - text: Gradescope
        #     url: https://sakai.duke.edu/portal/site/d55dc1df-28e1-4637-be6f-6ba7c848fabf/page/e6e5b35b-ae85-4d98-8c56-ec6c559db637
        #   - text: Gradebook
        #     url: https://sakai.duke.edu/portal/site/d55dc1df-28e1-4637-be6f-6ba7c848fabf/tool/1d0ca2ac-6304-46b2-a6ac-de5a93f677b2/

    style: docked
    search: true
    collapse-level: 1
    contents:
      - section: "Course information"
        contents:
          - href: course-syllabus.qmd
            text: Syllabus
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Computing"
        contents:
          - href: computing-access.qmd
            text: Access
          - href: computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing-cheatsheets.qmd
            text: Cheatsheets
      - section: "Project"
        contents:
          - href: project-description.qmd
            text: Description
          # - href: project-tips-resources.qmd
          #   text: Tips + resources

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Alexander Fisher"
    background: "#2774AE" # nice blue -- Spring 2023

format:
  html:
    theme:
      light: [cosmo, style/sta199.scss]
      #dark: [cosmo, style/sta199.scss, style/dark.scss]
    linkcolor: "#2774AE" # nice blue -- Spring 2023
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto

editor: visual
