---
title: "Syllabus"
---

::: {.content-visible when-format="html"}
[**Click here**](syllabus-spring23.pdf) **to download a PDF copy of the syllabus.**
:::

|                    |                                                                                |
|------------------|------------------------------------------------------|
| Course             | STA199-001                                                                     |
| Instructor         | Dr. Alexander Fisher ([alexander.fisher\@duke.edu](alexander.fisher@duke.edu)) |
| Head TA            | David Buch ([david.buch@duke.edu](david.buch@duke.edu))           |
| Course Coordinator | Edric Tam ([sta199\@duke.edu](sta199@duke.edu))                                |

Our course coordinator, Edric Tam, will handle all inquiries about late work, extensions and absences in accordance with the late policy described in the syllabus below.
Please send emails to [sta199\@duke.edu](sta199@duke.edu).

## Class time and location

|         |                     |                                |
|---------|---------------------|--------------------------------|
| Lecture | W/F: 10:15-11:30 AM | LSRC B101                      |
| Lab 1   | M: 10:15-11:30 AM   | Perkins LINK 087 (Classroom 3) |
| Lab 2   | M: 12:00-1:15 PM    | Perkins LINK 087 (Classroom 3) |
| Lab 3   | M: 1:45-3:00 PM     | Perkins LINK 087 (Classroom 3) |
| Lab 4   | M: 3:30-4:35 PM     | Perkins LINK 087 (Classroom 3) |
| Lab 5   | M: 5:15-6:30 PM     | Perkins LINK 087 (Classroom 3) |
| Lab 11  | M: 5:15 - 6:30 PM   | Perkins LINK 071 (Classroom 5) |

## Office hours

[Click here](https://docs.google.com/spreadsheets/d/16gf9dQ_41V628vKvFdS95JBOUKYSjuxJBo7OzPye-SI/edit?usp=sharing) for the instructor and TA office hours locations and Zoom links.
You are welcome to attend the office hours for **any** member of the teaching team, regardless of section.

## Textbooks

All books are **freely available online**.

|                                                                         |                          |                                   |                                                                                                                                  |
|---------------|---------------|---------------|--------------------------|
| [R for Data Science, 2e](https://r4ds.hadley.nz/)                       | Grolemund, Wickham       | O'Reilly, 2nd edition, 2022       | Hard copy only available of 1st edition                                                                                          |
| [Introduction to Modern Statistics](https://openintro-ims.netlify.app/) | Çetinkaya-Rundel, Hardin | OpenIntro Inc., 1st Edition, 2021 | Hard copy available [on Amazon](https://www.amazon.com/Introduction-Modern-Statistics-Mine-%C3%87etinkaya-Rundel/dp/1943450145/) |

## Course learning objectives

By the end of the semester, you will...

-   learn to explore, visualize, and analyze data in a reproducible manner
-   gain experience in data wrangling and munging, exploratory data analysis, predictive modeling, and data visualization
-   work on problems and case studies inspired by and based on real-world questions and data
-   learn to effectively communicate results through written assignments and project presentation
-   develop your own question about a data set of your choosing and use techniques from this class to answer the question

## Assessment

The activities and assessments in this course are designed to help you successfully achieve the course learning objectives.
They are designed to follow the **Prepare, Practice, Perform** format.

-   **Prepare**: Includes short videos, reading assignments, and lectures to introduce new concepts and ensure a basic comprehension of the material.
    The goal is to help you prepare for the in-class activities during lecture.

-   **Practice**: In-class application exercises where you will begin to master the concepts and methods introduced in the prepare assignment.
    The activities will graded for completion, as they are designed for you to gain experience with the statistical and computing techniques before working on graded assignments.

-   **Perform**: Includes labs, homework, exams, and the project.
    These assignments build upon the prepare and practice assignments and are the opportunity for you to demonstrate your understanding of the course material and how it is applied to analyze real-world data.

### Team work policy

The final project and several labs will be completed in teams.
GitHub commits will be used to measure individual contribution to the assignment.
All group members are expected to participate equally.
Commit history may be used to give individual team members different grades.
Your grade may differ from the rest of your group.

### Application exercises (practice)

Each lecture, we will work through application exercise (AEs).
These serve as notes you will fill in during class mixed with practice exercises.
Exercises which give you an opportunity to practice statistical concepts and code introduced in the prepare assignment.

Because these AEs are for practice, they will be graded based on completion, i.e., a good-faith effort has been made in attempting all parts.
Successful on-time completion of at least 80% of AEs will result in full credit for AEs in the final course grade.
To submit an AE, you simply need to push your completed AE to the designated repo in GitHub.

### Labs (perform)

In labs, you will apply the concepts discussed in lecture to various data analysis scenarios, with a focus on the computation.
Some lab assignments will be completed in teams, and all team members are expected to contribute equally to the completion of each assignment.
You are expected to use the team's git repository on the course's GitHub page as the central platform for collaboration.
Commits to this repository will be used as a metric of each team member's relative contribution for each lab, see team work policy above.
Lab assignments will be completed using Quarto, correspond to an appropriate GitHub repository, and be submitted for grading in Gradescope.

*The lowest lab grade will be dropped at the end of the semester.*

### Homework (perform)

In homework, you will apply what you've learned during lecture and lab to complete data analysis tasks.
You may discuss homework assignments with other students; however, homework should be completed and submitted individually.
Similar to lab assignments, homework must be typed up using Quarto and GitHub and submitted as a PDF in Gradescope.

Homework assignments are due at 5:00 PM ET on the indicated due date.

One homework assignment will be dedicated to a *statistics experience*.
The statistics experience is an opportunity to engage with statistics and data science outside of the classroom through podcasts, books, seminars, data analysis competitions, and other activities.
As you complete these experiences, the goal is to consider how the material you're learning in the course connects with society more broadly.

*The lowest homework grade will be dropped at the end of the semester.*

### Exams (perform)

There will be two, take-home, open-note exams.
Through these exams you have the opportunity to demonstrate what you've learned in the course thus far.
Each exam will include small analysis and computational tasks related to the content in the prepare, practice, and perform assignments.
More details about the content and structure of the exams will be discussed during the semester.

### Project (perform)

The purpose of the [project](project-description.html) is to apply what you've learned throughout the semester to analyze an interesting data-driven research question.
The project will be completed with your lab teams, and each team will present their work in video and in writing during the final exam period.
More information about the project will be provided during the semester.

## Grading

The final course grade will be calculated as follows:

| Category              | Percentage |
|-----------------------|------------|
| Homework              | 30%        |
| Labs                  | 15%        |
| Project               | 15%        |
| Exam 01               | 18%        |
| Exam 02               | 18%        |
| Application Exercises | 4%         |

The final letter grade will be determined based on the following thresholds:

| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |

## Course policies

**Inclusive community**: It is my intent that students from all backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength, and benefit.
It is my intent to present materials and activities that are respectful of diversity and in alignment with Duke's Commitment to Diversity and Inclusion.
Your suggestions are encouraged and appreciated.
Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

**Academic honesty:** You should be familiar with Duke's community standard: <https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard>

By enrolling in this course, you commit to upholding Duke's community standard reproduced as follows:

-   I will not lie, cheat, or steal in my academic endeavors;
-   I will conduct myself honorably in all my endeavors; and
-   I will act if the Standard is compromised.

Any violations in academic honesty standards as outlined in the Duke Community Standard and those specific to this course will **automatically result in a 0** for the assignment and will be reported to the Office of Student Conduct for further action.

Please abide by the following as you work on assignments in this course: - You may discuss lab assignments with other students; however, you may not directly share (or copy) code or write up with other students.
For team assignments, you may collaborate freely within your team.
You may discuss the assignment with other teams; however, you may not directly share (or copy) code or write up with another team.
Unauthorized sharing (or copying) of the code or write up will be considered a violation for all students involved.
- You may not discuss or otherwise work with others on the exams.
Unauthorized collaboration or using unauthorized materials will be considered a violation for all students involved.
More details will be given closer to the exam date.
- Reusing code: Unless explicitly stated otherwise, you may make use of online resources (e.g. Stack- Overflow) for coding examples on assignments.
If you directly use code from an outside source (or use it as inspiration), you must explicitly cite where you obtained the code.
Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

**Late policy:**

Homeworks and labs can be turned in within 72 hours of the deadline for grade penalty (5% off per day, stacks to 15% by the third day).
Exams cannot be turned in late and can only be excused under exceptional circumstances.
The Duke policy for illness requires a short-term illness report or a letter from the Dean; except in emergencies, all other absenteeism must be approved in advance (e.g., an athlete who must miss class may be excused by prior arrangement for specific days).
For emergencies, email notification is needed at the first reasonable time.

**Procedures for Requesting a Regrade**

Every effort will be made to mark your work accurately.
We are on your side, and want you to receive every point you have worked to earn.
However, sometimes grading mistakes happen.
If you believe that an error has been made, return the paper to the instructor within four days, stating your claim in writing.

The following claims will be considered for re-grading:

(i) points are not totaled correctly;

(ii) the grader did not see a correct answer that is on your paper;

(iii) your answer is the same as the correct answer, but in a different form (e.g., you wrote a correct answer as 1/3 and the grader was looking for .333);

(iv) your answer to a free response question is essentially correct but stated slightly differently than the grader's expectation.

The following claims will not be considered for re-grading:

(v) arguments about the number of points lost;

<!-- -->

(vi) arguments about question wording.

Considering re-grades consumes time and resources that TAs and the instructor would rather spend helping you understand material.
Please bring only claims of type (i), (ii), (iii), or (iv) to our attention.

**Communication:** All lecture notes, assignment instructions, an up-to-date schedule, and other course materials may be found on the course website.
Announcements will be emailed to the class through sakai.
Please check your email regularly to ensure you have the latest announcements for the course.
For quick communication with your peers and the teaching team, see the course slack for general questions and discussion.

**Accessibility:** If there is any portion of the course that is not accessible to you due to challenges with technology or the course format, please let me know so we can make appropriate accommodations.
The Student Disability Access Office (SDAO) is available to ensure that students are able to engage with their courses and related assignments.
Students should be in touch with the Student Disability Access Office to request or update accommodations under these circumstances.
Please note that accommodations are not retroactive and disability accommodations cannot be provided until a Faculty Accommodation Letter has been given to me.
Please contact SDAO for more information: [sdao\@duke.edu](sdao@duke.edu) or [access.duke.edu](https://access.duke.edu).

## Additional resources

Student mental health and wellness are of primary importance at Duke, and the university offers resources to support students in managing daily stress and self-care.
Duke offers several resources for students to seek assistance on coursework and to nurture daily habits that support overall well-being, some of which are listed below

-   The Academic Resource Center: (919) 684-5917, [theARC\@duke.edu](theARC@duke.edu), or [arc.duke.edu](https://arc.duke.edu).
    The Academic Resource Center (the ARC) offers services to support students academically during their undergraduate careers at Duke.
    The ARC can provide support with time management, academic skills and strategies, course-specific tutoring, and more.
    ARC services are available free to any Duke undergraduate student, studying any discipline.

-   DuWell: (919) 681-8421, provides Moments of Mindfulness (stress management and resilience building) and meditation programming (Koru workshop) to assist students in developing a daily emotional well-being practice.
    To see schedules for programs please see <https://studentaffairs.duke.edu/duwell>.
    All are welcome and no experience necessary.

If your mental health concerns and/or stressful events negatively affect your daily emotional state, academic performance, or ability to participate in your daily activities, many resources are available to help you through difficult times.
Duke encourages all students to access these resources.

-   DukeReach.
    Provides comprehensive outreach services to identify and support students in managing all aspects of well-being.
    If you have concerns about a student's behavior or health visit the website for resources and assistance: <https://students.duke.edu/wellness/dukereach/>

-   Counseling and Psychological Services (CAPS).
    CAPS services include individual and group counseling services, psychiatric services, and workshops.
    To initiate services, walk-in/call-in 9-4 M,W,Th,F and 9-6 Tuesdays.
    CAPS also provides referral to off- campus resources for specialized care.

    (919) 660-1000 or <https://students.duke.edu/wellness/caps/>

-   TimelyCare (formerly known as Blue Devils Care).
    An online platform that is a convenient, confidential, and free way for Duke students to receive 24/7 mental health support through TalkNow and scheduled counseling.
    bluedevilscare.duke.edu
