{
  "hash": "2ecb92c93db082256eb9d410c21483b9",
  "result": {
    "markdown": "---\ntitle: \"Multiple regression II\"\nsubtitle: \"STA 199\"\neditor: source\nformat: html\nexecute:\n  error: true\n---\n\n\n## Bulletin\n\n-   this `ae` is **due for grade**. Push your completed ae to GitHub within 48 hours to receive credit\n-   homework 03 released today\n-   final project instructions\n\n## Getting started\n\nClone *your* `ae14-username` repo from the [GitHub organization](https://github.com/sta199-sp23-1/).\n\n\n## Warm-up\n\nCheck you understanding! Answer the following...\n\n1. To \"fit\" a linear model means...[fill in the blank]\n\n2. Is $y = \\beta_0 + \\beta_1 \\log(x_1)+ \\beta_2 x_2^2 + \\epsilon$ a linear model? Why or why not?\n\n## Today\n\nBy the end of today you will...\n\n- fit and interpret models with categorical predictors\n- fit and interpret models with interactive effects\n\n## Load packages and data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(palmerpenguins)\n```\n:::\n\n\nToday we will return to our Palmer penguins data set\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(penguins)\n```\n:::\n\n\nUse `?penguins` or [click here](https://github.com/allisonhorst/palmerpenguins) for more info.\n\n## Notes\n\n## Main effects\n\nUp until now, we've seen models that look like this:\n\n\n$$\ny = \\beta_0 + \\beta_1 x_1 + \\beta_2 x_2 + \\ldots + \\epsilon\n$$\n\n\nHere's an example:\n\n$y$: body mass (g)\n\n$x_1$: bill length (mm)\n\n$x_2$: 1 if island Dream, 0 otherwise\n\n$x_3$: 1 if island Torgersen, 0 otherwise\n\n\n$$\ny = \\beta_0 + {\\beta_1} x_1 + {\\beta_2} x_2 + {\\beta_3} x_3 + \\epsilon\n$$\n\n\nNotice that \n\n- We have a categorical predictor `island` that takes three values: Dream, Torgersen, and Biscoe.\n\n- Despite taking three values, there are only two island variables in the model. One for `Dream`  and one for `Torgersen`. Biscoe island is considered the default. This always occurs when we have a categorical variable -- one category is considered the default.\n\n- Bill length only impacts body mass via the term $\\beta_1 x_1$. \n\n- $x_2$ and $x_3$ can be thought of as turning on or off a constant.\n\nLet's visualize the main effects model below.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](ae-14_files/figure-html/main-1.png){width=672}\n:::\n:::\n\n\n\nWe can fit the \"main effects\" model above with our standard procedure:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmain_fit = linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(body_mass_g ~ bill_length_mm + island, data = penguins)\n\n  main_fit %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 4 × 5\n  term            estimate std.error statistic  p.value\n  <chr>              <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)       1226.     243.        5.04 7.58e- 7\n2 bill_length_mm      77.1      5.31     14.5  1.66e-37\n3 islandDream       -919.      58.6     -15.7  5.15e-42\n4 islandTorgersen   -523.      85.5      -6.12 2.64e- 9\n```\n:::\n:::\n\n\nIf we want to know how bill length relates to body mass for penguins on island Biscoe, we plug in $0$ for $x_2$ and $x_3$ and write the resulting model. If we repeat as appropriate for each island, the result is 3 separate fitted models:\n\nBiscoe:\n\n\n$$\n\\hat{y} = 1225.8 + 77.1 x_1 \n$$\n\n\nDream:\n\n\n$$\n\\hat{y} = 1225.8 + 77.1 x_1 - 919.1\n$$\n\n\n\nTorgersen:\n\n\n$$\n\\hat{y} = 1225.8 + 77.1 x_1 -523.3\n$$\n\n\nNotice that in each case, the slope associated with bill length ($x_1$) is the same.\n\n### Interaction effects\n\nInteraction effect models contain products of predictors, e.g.\n\n\n$$\ny = {\\beta_0} + {\\beta_1} x_1 + {\\beta_2} x_2 + {\\beta_3} x_3 +  {\\beta_4} x_1 x_2 + {\\beta_5} x_1 x_3 + \\epsilon\n$$\n\n\nHere we have an interaction between bill length and island ($\\beta_4 x_1 x_2$ and $\\beta_5 x_1 x_3$).\n\nTake-away idea: $x_1$ is related to $y$ but the relationship changes depending on $x_2$ and $x_3$.\n\nThe simplest scenario is one of \"group membership\". In other words, knowing the group your measurement belongs to affects the relationship between $x_1$ and $y$.\n\nHere, we see bill length ($x_1$) show up multiple times in our linear model paired with islands. In other words, the relationship between bill length and body mass depends on the island a penguin is from.\n\nWe fit this interaction model using the code below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninteraction_fit = linear_reg() %>%\n  set_engine(\"lm\") %>%\n  fit(body_mass_g ~ bill_length_mm * island, data = penguins)\n\n  interaction_fit %>%\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  term                           estimate std.error statistic  p.value\n  <chr>                             <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)                     -1726.     292.       -5.91 8.43e- 9\n2 bill_length_mm                    142.       6.42     22.2  9.14e-68\n3 islandDream                      4479.     395.       11.3  2.03e-25\n4 islandTorgersen                  2871.     778.        3.69 2.60e- 4\n5 bill_length_mm:islandDream       -121.       8.77    -13.8  1.93e-34\n6 bill_length_mm:islandTorgersen    -76.6     19.5      -3.92 1.07e- 4\n```\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](ae-14_files/figure-html/interaction-1.png){width=672}\n:::\n:::\n\n\nInterpreting interactions can be difficult, especially without writing things down. To make it easier, we will compare the implied linear models:\n\nPlug in 0 for `islandDream` ($x_2$) and 0 for `islandTorgersen` ($x_3$) to get the linear model for `islandBiscoe` penguins\n\nPlug in 1 for `islandDream` ($x_2$) and 0 for `islandTorgersen` ($x_3$) to get the linear model for `islandDream` penguins\n\nPlug in 0 for `islandDream` ($x_2$) and 1 for `islandTorgersen` ($x_3$) to get the linear model for `islandTorgersen` penguins\n\n- Biscoe fitted model:\n\n\n$$\n\\hat{y} = -1726.0+ 142.3 x_1\n$$\n\n\n- Dream fitted model:\n\n\n$$\n\\hat{y} = -1726.0 + 142.3 x_1 + 4478.7 -120.6 x_1\n$$\n\n\nCombine terms:\n\n\n$$\n\\hat{y} = 2752.7 + 21.7 x_1 \n$$\n\n\n#### Exercise 1 \n\nWrite out the fitted model for Torgersen island below.\n\n- Torgersen model:\n\n$$\n\\hat{y} = [\\text{write here}]\n$$\n\n\n### Interpreting\n\nNow we can interpret the interaction model by comparing bill length slopes between islands.\n\n- For a unit increase in bill length of a penguin from the island Dream, how much do we expect the body mass to increase?\n\n#### Exercise 2\n\n- You measured the bill length of a penguin from island Biscoe and a penguin from island Torgersen a year ago. You re-measure them today and find the bill length of each one grew by exactly 2 mm. How much mass do you expect each penguin to have gained?\n\n#### Exercise 3\n\nAre the intercepts meaningful?\n\n\n#### Exercise 4\n\nIs the relationship between Body mass (g) and Bill depth (mm) positive or negative? Create a convincing argument from the data.\n\n#### Exercise 5\n\nBuild a linear model of body mass using bill depth and one other predictor of your choosing (hint: see previous exercise!)\n\n- Write out a linear model with both predictors and fit the model.\n\n- Fit the linear model\n\n- Do you prefer this model to the interaction effects model from a previous exercise? Why?\n\n\n\n",
    "supporting": [
      "ae-14_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}